<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8dab6a80154baebcc28aff395f4b07a5
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8dab6a80154baebcc28aff395f4b07a5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8dab6a80154baebcc28aff395f4b07a5::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8dab6a80154baebcc28aff395f4b07a5::$classMap;

        }, null, ClassLoader::class);
    }
}
